package sh.hell.compactchess.game;

@SuppressWarnings({"WeakerAccess", "UnusedReturnValue", "unused"})
public enum CountryCode
{
	Afghanistan("AFG", "Afghanistan"),
	Aboard_aircraft("AIR", "Aboard aircraft"),
	Albania("ALB", "Albania"),
	Algeria("ALG", "Algeria"),
	Andorra("AND", "Andorra"),
	Angola("ANG", "Angola"),
	Antigua("ANT", "Antigua"),
	Argentina("ARG", "Argentina"),
	Armenia("ARM", "Armenia"),
	Antarctica("ATA", "Antarctica"),
	Australia("AUS", "Australia"),
	Azerbaijan("AZB", "Azerbaijan"),
	Bangladesh("BAN", "Bangladesh"),
	Bahrain("BAR", "Bahrain"),
	Bahamas("BHM", "Bahamas"),
	Belgium("BEL", "Belgium"),
	Bermuda("BER", "Bermuda"),
	Bosnia_and_Herzegovina("BIH", "Bosnia and Herzegovina"),
	Belarus("BLA", "Belarus"),
	Bulgaria("BLG", "Bulgaria"),
	Belize("BLZ", "Belize"),
	Bolivia("BOL", "Bolivia"),
	Barbados("BRB", "Barbados"),
	Brazil("BRS", "Brazil"),
	Brunei("BRU", "Brunei"),
	Botswana("BSW", "Botswana"),
	Canada("CAN", "Canada"),
	Chile("CHI", "Chile"),
	Columbia("COL", "Columbia"),
	Costa_Rica("CRA", "Costa Rica"),
	Croatia("CRO", "Croatia"),
	Czechoslovakia("CSR", "Czechoslovakia"),
	Cuba("CUB", "Cuba"),
	Cyprus("CYP", "Cyprus"),
	Denmark("DEN", "Denmark"),
	Dominican_Republic("DOM", "Dominican Republic"),
	Ecuador("ECU", "Ecuador"),
	Egypt("EGY", "Egypt"),
	England("ENG", "England"),
	Spain("ESP", "Spain"),
	Estonia("EST", "Estonia"),
	Faroe_Islands("FAI", "Faroe Islands"),
	Fiji("FIJ", "Fiji"),
	Finland("FIN", "Finland"),
	France("FRA", "France"),
	Gambia("GAM", "Gambia"),
	Guernsey_Jersey("GCI", "Guernsey-Jersey"),
	Georgia("GEO", "Georgia"),
	Germany("GER", "Germany"),
	Ghana("GHA", "Ghana"),
	Greece("GRC", "Greece"),
	Guatemala("GUA", "Guatemala"),
	Guyana("GUY", "Guyana"),
	Haiti("HAI", "Haiti"),
	Hong_Kong("HKG", "Hong Kong"),
	Honduras("HON", "Honduras"),
	Hungary("HUN", "Hungary"),
	India("IND", "India"),
	Ireland("IRL", "Ireland"),
	Iran("IRN", "Iran"),
	Iraq("IRQ", "Iraq"),
	Iceland("ISD", "Iceland"),
	Israel("ISR", "Israel"),
	Italy("ITA", "Italy"),
	Ivory_Coast("IVO", "Ivory Coast"),
	Jamaica("JAM", "Jamaica"),
	Japan("JAP", "Japan"),
	Jordan("JRD", "Jordan"),
	Yugoslavia_JUG("JUG", "Yugoslavia"),
	Kazakhstan("KAZ", "Kazakhstan"),
	Kenya("KEN", "Kenya"),
	Kyrgyzstan("KIR", "Kyrgyzstan"),
	Kuwait("KUW", "Kuwait"),
	Latvia("LAT", "Latvia"),
	Lebanon("LEB", "Lebanon"),
	Libya("LIB", "Libya"),
	Liechtenstein("LIC", "Liechtenstein"),
	Lithuania("LTU", "Lithuania"),
	Luxembourg("LUX", "Luxembourg"),
	Malaysia("MAL", "Malaysia"),
	Mauritania("MAU", "Mauritania"),
	Mexico("MEX", "Mexico"),
	Mali("MLI", "Mali"),
	Malta("MLT", "Malta"),
	Monaco("MNC", "Monaco"),
	Moldova("MOL", "Moldova"),
	Mongolia("MON", "Mongolia"),
	Mozambique("MOZ", "Mozambique"),
	Morocco("MRC", "Morocco"),
	Mauritius("MRT", "Mauritius"),
	Myanmar("MYN", "Myanmar"),
	Nicaragua("NCG", "Nicaragua"),
	The_Internet("NET", "The Internet"),
	Nigeria("NIG", "Nigeria"),
	Netherlands_Antilles("NLA", "Netherlands Antilles"),
	Netherlands("NLD", "Netherlands"),
	Norway("NOR", "Norway"),
	New_Zealand("NZD", "New Zealand"),
	Austria("OST", "Austria"),
	Pakistan("PAK", "Pakistan"),
	Palestine("PAL", "Palestine"),
	Panama("PAN", "Panama"),
	Paraguay("PAR", "Paraguay"),
	Peru("PER", "Peru"),
	Philippines("PHI", "Philippines"),
	Papua_New_Guinea("PNG", "Papua New Guinea"),
	Poland("POL", "Poland"),
	Portugal("POR", "Portugal"),
	Peoples_Republic_of_China("PRC", "People's Republic of China"),
	Puerto_Rico("PRO", "Puerto Rico"),
	Qatar("QTR", "Qatar"),
	Indonesia("RIN", "Indonesia"),
	Romania("ROM", "Romania"),
	Russia("RUS", "Russia"),
	South_Africa("SAF", "South Africa"),
	El_Salvador("SAL", "El Salvador"),
	Scotland("SCO", "Scotland"),
	At_Sea("SEA", "At Sea"),
	Senegal("SEN", "Senegal"),
	Seychelles("SEY", "Seychelles"),
	Singapore("SIP", "Singapore"),
	Slovenia("SLV", "Slovenia"),
	San_Marino("SMA", "San Marino"),
	Aboard_spacecraft("SPC", "Aboard spacecraft"),
	Sri_Lanka("SRI", "Sri Lanka"),
	Sudan("SUD", "Sudan"),
	Surinam("SUR", "Surinam"),
	Sweden("SVE", "Sweden"),
	Switzerland("SWZ", "Switzerland"),
	Syria("SYR", "Syria"),
	Thailand("TAI", "Thailand"),
	Turkmenistan("TMT", "Turkmenistan"),
	Turkey("TRK", "Turkey"),
	Trinidad_and_Tobago("TTO", "Trinidad and Tobago"),
	Tunisia("TUN", "Tunisia"),
	United_Arab_Emirates("UAE", "United Arab Emirates"),
	Uganda("UGA", "Uganda"),
	Ukraine("UKR", "Ukraine"),
	Unknown("UNK", "Unknown"),
	Uruguay("URU", "Uruguay"),
	United_States_of_America("USA", "United States of America"),
	Uzbekistan("UZB", "Uzbekistan"),
	Venezuela("VEN", "Venezuela"),
	British_Virgin_Islands("VGB", "British Virgin Islands"),
	Vietnam("VIE", "Vietnam"),
	US_Virgin_Islands("VUS", "U.S. Virgin Islands"),
	Wales("WLS", "Wales"),
	Yemen("YEM", "Yemen"),
	Yugoslavia("YUG", "Yugoslavia"),
	Zambia("ZAM", "Zambia"),
	Zimbabwe("ZIM", "Zimbabwe"),
	Zaire("ZRE", "Zaire");

	public final String code;
	public final String name;

	CountryCode(String code, String name)
	{
		this.code = code;
		this.name = name;
	}

	public static CountryCode fromCode(String code)
	{
		for(CountryCode countryCode : CountryCode.values())
		{
			if(countryCode.code.equalsIgnoreCase(code))
			{
				return countryCode;
			}
		}
		return null;
	}
}
